# Generated by Django 2.1.4 on 2019-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('constructorId', models.IntegerField(primary_key=True, serialize=False)),
                ('constructorRef', models.TextField()),
                ('name', models.TextField()),
                ('nationality', models.TextField()),
                ('ulr', models.URLField()),
            ],
        ),
    ]
