# Generated by Django 2.1.4 on 2019-08-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructor',
            old_name='ulr',
            new_name='url',
        ),
    ]
