# Generated by Django 2.1.4 on 2019-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('circuitId', models.IntegerField(primary_key=True, serialize=False)),
                ('circuitRef', models.TextField()),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('country', models.TextField()),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
