# Generated by Django 2.1.4 on 2019-08-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusId', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
        ),
    ]
