# Generated by Django 2.1.4 on 2019-08-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.IntegerField()),
                ('driverRef', models.TextField()),
                ('number', models.IntegerField()),
                ('code', models.TextField()),
                ('forename', models.TextField()),
                ('surname', models.TextField()),
                ('dob', models.TextField()),
                ('nationality', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
