# Generated by Django 2.1.4 on 2019-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20190823_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
