# Generated by Django 2.1.4 on 2019-08-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('raceId', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuitId', models.IntegerField()),
                ('name', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField(null=True)),
                ('url', models.TextField()),
            ],
        ),
    ]
